/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AiEndpoint": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "DATABASE_CONNECTIONS": {
      "primary": string
      "replicas": any
    }
    "ELEVEN_LABS_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ELEVEN_LABS_VOICE_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ImageResizer": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MyVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "NEON_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Realtime": {
      "authorizer": string
      "endpoint": string
      "type": "sst.aws.Realtime"
    }
    "TransformedImages": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Uploads": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Web": {
      "type": "sst.aws.Remix"
      "url": string
    }
    "WsApi": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
  }
}
