/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import 'sst'
declare module 'sst' {
  export interface Resource {
    AiEndpoint: {
      name: string
      type: 'sst.aws.Function'
      url: string
    }
    Api: {
      name: string
      type: 'sst.aws.Function'
      url: string
    }
    Auth: {
      name: string
      type: 'sst.aws.Function'
      url: string
    }
    Bucket: {
      name: string
      type: 'sst.aws.Bucket'
    }
    CloudflareApi: {
      type: 'sst.cloudflare.Worker'
      url: string
    }
    RukumaBucket: {
      type: 'sst.cloudflare.Bucket'
    }
    Web: {
      type: 'sst.aws.Remix'
      url: string
    }
  }
}
