/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AiEndpoint": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "DbAppUserCreds": {
      "database": string
      "host": string
      "password": string
      "type": "sst.sst.Linkable"
      "username": string
    }
    "DbMigrationsUserCreds": {
      "database": string
      "host": string
      "password": string
      "type": "sst.sst.Linkable"
      "username": string
    }
    "ELEVEN_LABS_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ELEVEN_LABS_VOICE_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Electric": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "ImageResizer": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MyVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "NEON_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NeonDb": {
      "host": string
      "neonBranchId": string
      "neonBranchName": string
      "type": "sst.sst.Linkable"
    }
    "Realtime": {
      "authorizer": string
      "endpoint": string
      "type": "sst.aws.Realtime"
    }
    "TransformedImages": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Uploads": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Web": {
      "type": "sst.aws.Remix"
      "url": string
    }
  }
}
