/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AiEndpoint": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Auth": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "BadBatchWeb": {
      "type": "sst.aws.Remix"
      "url": string
    }
    "Bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "DATABASE_CONNECTIONS": {
      "primary": string
      "replicas": any
    }
    "ImageResizer": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "NEON_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TransformedImages": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Uploads": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Web": {
      "type": "sst.aws.Remix"
      "url": string
    }
  }
}
